export const convertUserFromServerFormat = (user) => {
   const {
      avatar_url: avatar,
      bio,
      blog,
      company,
      created_at: createdAt,
      email,
      events_url: eventsUrl,
      followers,
      followers_url: followersUrl,
      following,
      following_url: followingUrl,
      gists_url: gistsUrl,
      gravatar_id: gravatarId,
      hireable,
      html_url: htmlUrl,
      id,
      location,
      login,
      name,
      node_id: nodeId,
      organizations_url: organizationsUrl,
      public_gists: publicGists,
      public_repos: publicRepos,
      received_events_url: receivedEventsUrl,
      repos_url: reposUrl,
      site_admin: siteAdmin,
      starred_url: starredUrl,
      subscriptions_url: subscriptionsUrl,
      twitter_username: twitterUsername,
      type,
      updated_at: updatedAt,
      url,
   } = user;
   return {
      avatar,
      bio,
      blog,
      company,
      createdAt,
      email,
      eventsUrl,
      followers,
      followersUrl,
      following,
      followingUrl,
      gistsUrl,
      gravatarId,
      hireable,
      htmlUrl,
      id,
      location,
      login,
      name,
      nodeId,
      organizationsUrl,
      publicGists,
      publicRepos,
      receivedEventsUrl,
      reposUrl,
      siteAdmin,
      starredUrl,
      subscriptionsUrl,
      twitterUsername,
      type,
      updatedAt,
      url,
   };
};
